# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("ip_hash", models.CharField(blank=True, max_length=50)),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-reported_at"],
            },
        ),
    ]
